### ISSUE TITLE
How do I implement UnmarshalPlist?

### ISSUE THREAD

**Issue by henrahmagix** [micromdm/plist#14]
I'm a bit confused about how to use/implement UnmarshalPlist. What am I meant to pass to the function `func (i interface{}) error`? When I pass the struct, I get an infinite loop.

My use case is I'm trying to unmarshal an iOS Workflow plist, but I'm stuck on the key `WFTextActionText` that can either be `<string>` or `<dict>`. I thought I could implement `UnmarshalPlist` on the struct that holds `WFTextActionText` to determine whether to set a `WFTextActionTextString` or `WFTextActionTextDict` value.

Thanks in advanced =)

Example plist and Go file: https://gist.github.com/henrahmagix/7b8909a02dcd326aa29dcd46be1dd8c6

Example string:
```xml
<key>WFTextActionText</key>
<string>City 1, state 1,country 1</string>
```
Example dict:
```xml
<key>WFTextActionText</key>
<dict>
	<key>Value</key>
	<dict>
		<key>attachmentsByRange</key>
		<dict>
			<key>{13, 1}</key>
			<dict>
				<key>Type</key>
				<string>Variable</string>
				<key>VariableName</key>
				<string>State</string>
			</dict>
			<key>{23, 1}</key>
			<dict>
				<key>Type</key>
				<string>Variable</string>
				<key>VariableName</key>
				<string>Country</string>
			</dict>
			<key>{5, 1}</key>
			<dict>
				<key>Type</key>
				<string>Variable</string>
				<key>VariableName</key>
				<string>City</string>
			</dict>
		</dict>
		<key>string</key>
		<string>City=￼ State=￼ Country=￼</string>
	</dict>
	<key>WFSerializationType</key>
	<string>WFTextTokenString</string>
</dict>
```

**Comment by jpap** [comment]
I am hitting this at the moment also, and have proposed #18 to address it.

For the existing interface here, you have to call the provided function with the unmarshaled value.  You implement the `Unmarshaler` interface on your custom type.

**Comment by henrahmagix** [comment]
Thanks @jessepeterson!
