### ISSUE TITLE
Improve custom unmarshaling

### ISSUE THREAD

**Issue by jpap** [micromdm/plist#18]
## A new interface

Currently we have the `Unmarshaler` interface for this, but it relies on being able to implement that interface on any custom type.  When that type exists in another package that we do not have control over, we can't use the interface and instead must unmarshal manually, which is a lot of work.

I would suggest adding an optional callback func in `Decoder` that can be called when we do not know how to otherwise unmarshal a value:
```
type UnmarshalUnknownFunc func(
   plistValue interface{},
   marshalType reflect.Type,
) (
   unmarshaledValue interface{},
   ok bool,
   err error,
)

type Decoder struct {
   // existing fields...

   // When a type is unknown during unmarshaling, we call this function when
   // non-nil, to provide the unmarshaled value.  The callback can indicate
   // that the value cannot be unmarshaled, in which case it is skipped.
   OnUnmarshalUnsupported UnmarshalUnknownFunc
}
```
This would obviously require users to use `New{XML,Binary}Decoder` to be able to set this callback func, over using `Unmarshal` directly.

Furthermore, it would allow unknown types to be "skipped", when `ok` is false.  Currently we just fail with an error.

## Improving the existing interface

Separately, the current interface is a little awkward with the argument being a function, as seen in #14. A more straightforward interface might instead be:
```
type Unmarshaler interface {
   UnmarshalPlist(plistValue interface{}) (unmarshaledValue interface{}, err error)
}
```

**Comment by groob** [comment]
IMO the UnmarshalPlist func is fine, just needs documentation.

**Comment by jessepeterson** [comment]
Closing per notes in #21. Thanks!
