### ISSUE TITLE
Plist failing plutil -lint is successfully parsed

### ISSUE THREAD

**Issue by jessepeterson** [micromdm/plist#3]
A plist that begins with this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
test
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
```

.. is successfully parsed. Note the `test` after the docstring. While apparently valid XML definitely not a valid plist.

**Comment by groob** [comment]
Interesting. How did you happen to create this sort of plist?

**Comment by jessepeterson** [comment]
A text editor. I was intentionally trying to muck it up to test error handling, but low and behold: it took it. :)
